package com.cuee.domain.safety

enum class StopReason {
    NOT_KORAIL_APP,
    SENSITIVE_LOGIN,
    SENSITIVE_PERSONAL_INFO,
    SENSITIVE_PAYMENT,
    SENSITIVE_AUTH_CODE,
    SENSITIVE_CONFIRMATION,
    LOW_CONFIDENCE,
    OVERLAPPING_CANDIDATES,
    NO_TARGET,
    USER_CANCELLED,
    MAX_STEPS_REACHED
}
